import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from '../components/Sidebar'; // Adjust path as necessary
import "./globals.css"; // Make sure global styles are included

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "To Do Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex min-h-screen">
          <Sidebar />
          <main className="flex-1 p-4 bg-gray-100 pl-24 lg:pl-60">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
